# Note: jekyll must be rebuilt to apply changes from this file.

# Run this command when generating production site.
# export JEKYLL_ENV=production


plugins: [jekyll-paginate]

# content will be regenerated on-the-fly if changes are made.
auto: true

name: "Double Jump Electric"
author: "Sonya Vasquez"
description: ""
copyright: "&copy; Sonya Vasquez 2025"

url: "http://doublejumpelectric.com"
project_images_dir: "/img/projects"

paginate: 10

#markdown: rdiscount
markdown: kramdown
kramdown:
    parse_block_html: true
permalink: pretty
